version: "3"
services:
  client_dev:
    build: ./client
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /home/app/client
    volumes:
      - ./client:/home/app/client
  api_dev:
    build: ./api
    command: sh -c "npm install && node index.js"
    ports:
      - 3001:3001
    working_dir: /home/app/api
    volumes:
      - ./api:/home/app/api
  #   depends_on:
  #     - db
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_DB=postgresdb
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   volumes:
  #     - ./db/data/postgres:/var/lib/postgresql/data
  #     - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  #   ports:
  #     - 5432:5432